# -*- coding: utf-8 -*-
"""2 : EDA_Object_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RFzZNrSy8Sgs4JXgB0l_w7ai3puRyiDV
"""

# Install Kaggle tooling used by this notebook
!pip install -q kaggle kagglehub

# Optional Kaggle API credential setup.
# Run this only if you uploaded kaggle.json to the current Colab session.
!mkdir -p ~/.kaggle
!if [ -f kaggle.json ]; then mv kaggle.json ~/.kaggle/kaggle.json && chmod 600 ~/.kaggle/kaggle.json; else echo "kaggle.json not found; skipping credential setup."; fi

import os
import cv2
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm

try:
    from IPython.display import Image, display
except ImportError:
    Image = None
    def display(obj=None, *args, **kwargs):
        print(obj)

sns.set_theme(style="whitegrid")

"""After uploading `kaggle.json`, move it to the `.kaggle` directory and set appropriate permissions:

Now you can download datasets from Kaggle. You'll need the dataset's API command, which can be found on the dataset's page under the 'Data' tab, usually at the bottom. It looks something like `kaggle datasets download -d user/dataset-name`. For example, let's download the 'titanic' dataset:

Finally, if the downloaded file is a zip archive, you'll need to unzip it:
"""

import kagglehub

# Download latest version of the VeRi dataset
path = kagglehub.dataset_download("abhyudaya12/veri-vehicle-re-identification-dataset")

print("Path to dataset files:", path)

import os

# Define paths
train_dir = os.path.join(path, 'VeRi', 'image_train')
test_dir = os.path.join(path, 'VeRi', 'image_test')
query_dir = os.path.join(path, 'VeRi', 'image_query')

IMAGE_EXTENSIONS = ('.jpg', '.jpeg', '.png')

def list_images(directory):
    """Return sorted image filenames from a directory, or an empty list if it is missing."""
    if not os.path.isdir(directory):
        print(f"Directory not found: {directory}")
        return []
    return sorted(f for f in os.listdir(directory) if f.lower().endswith(IMAGE_EXTENSIONS))

train_images = list_images(train_dir)
test_images = list_images(test_dir)
query_images = list_images(query_dir)

train_count = len(train_images)
test_count = len(test_images)
query_count = len(query_images)

print(f"--- VeRi Dataset Summary ---")
print(f"Training images: {train_count}")
print(f"Test images:     {test_count}")
print(f"Query images:    {query_count}")
print(f"Total images:    {train_count + test_count + query_count}")

"""### Dataset Split Description

- **Train Set (`image_train`)**: Contains 37,778 images of 576 vehicles. This set is used to train the deep learning model to learn feature representations of vehicles.
- **Test Set (`image_test`)**: Contains 11,579 images of 200 vehicles (different from the training IDs). These are the 'gallery' images used to search against.
- **Query Set (`image_query`)**: Contains 1,678 images. These are the 'probe' images. In a real-world scenario, you take a query image and try to find matches in the test set gallery.
"""

labels = ['Train', 'Test', 'Query']
counts = [train_count, test_count, query_count]
colors = ['#4CAF50', '#2196F3', '#FFC107']

plt.figure(figsize=(10, 6))
plt.bar(labels, counts, color=colors)
plt.title('VeRi Dataset Distribution')
plt.ylabel('Number of Images')

# Add count labels on top of bars
for i, count in enumerate(counts):
    plt.text(i, count + 500, str(count), ha='center', fontweight='bold')

plt.show()

# Display one training image
if train_images:
    sample_image_name = train_images[0]
    sample_image_path = os.path.join(train_dir, sample_image_name)

    img = cv2.imread(sample_image_path)
    if img is None:
        print(f"Failed to load image: {sample_image_path}")
    else:
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        plt.figure(figsize=(8, 6))
        plt.imshow(img_rgb)
        plt.title(f"Sample Training Image: {sample_image_name}")
        plt.axis('off')
        plt.show()

        print(f"Loaded Image Path: {sample_image_path}")
        print(f"Image Shape: {img.shape}")
        print(f"Total training images found: {len(train_images)}")
else:
    print("No images found in the image_train directory.")

# Display one testing image
if test_images:
    sample_image_name = test_images[0]
    sample_image_path = os.path.join(test_dir, sample_image_name)

    img = cv2.imread(sample_image_path)
    if img is None:
        print(f"Failed to load image: {sample_image_path}")
    else:
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        plt.figure(figsize=(8, 6))
        plt.imshow(img_rgb)
        plt.title(f"Sample Testing Image: {sample_image_name}")
        plt.axis('off')
        plt.show()

        print(f"Loaded Image Path: {sample_image_path}")
        print(f"Image Shape: {img.shape}")
        print(f"Total testing images found: {len(test_images)}")
else:
    print("No images found in the image_test directory.")

## Measure max-side distribution for detecting outliers

def get_max_side_records(image_list, directory, dataset_name):
    records = []
    for img_name in tqdm(image_list, desc=f"Scanning {dataset_name}"):
        img_path = os.path.join(directory, img_name)
        img_temp = cv2.imread(img_path)
        if img_temp is not None:
            h, w = img_temp.shape[:2]
            records.append({
                'dataset': dataset_name,
                'image': img_name,
                'width': w,
                'height': h,
                'max_side': max(h, w),
            })
    return records

max_side_records = []
max_side_records.extend(get_max_side_records(train_images, train_dir, 'Train'))
max_side_records.extend(get_max_side_records(test_images, test_dir, 'Test'))

df_dist = pd.DataFrame(max_side_records, columns=['dataset', 'image', 'width', 'height', 'max_side'])

max_side_train = int(df_dist.loc[df_dist['dataset'] == 'Train', 'max_side'].max()) if not df_dist[df_dist['dataset'] == 'Train'].empty else 0
max_side_test = int(df_dist.loc[df_dist['dataset'] == 'Test', 'max_side'].max()) if not df_dist[df_dist['dataset'] == 'Test'].empty else 0

print("\nResults:")
print(f"- Max side in Trainset: {max_side_train} px")
print(f"- Max side in Testset:  {max_side_test} px")
display(df_dist.head())

"""# Unclean : Distribution of Image Max Side Lengths (Training Set)"""

# Filtering only training data for this specific chart
train_only_df = df_dist[df_dist['dataset'] == 'Train']

if train_only_df.empty:
    print("No training image dimensions available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(data=train_only_df, x='max_side', bins=50, kde=True, color='#4CAF50')
    plt.axvline(max_side_train, color='red', linestyle='--', label=f'Maximum: {max_side_train}px')

    plt.title('Distribution of Image Max Side Lengths (Training Set)')
    plt.xlabel('Max Side Length (pixels)')
    plt.ylabel('Count of Images')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

"""# Unclean : Distribution of Image Max Side Lengths (Testing Set)"""

# Filtering only testing data for this specific chart
test_only_df = df_dist[df_dist['dataset'] == 'Test']

if test_only_df.empty:
    print("No testing image dimensions available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(data=test_only_df, x='max_side', bins=50, kde=True, color='#2196F3')
    plt.axvline(max_side_test, color='red', linestyle='--', label=f'Maximum: {max_side_test}px')

    plt.title('Distribution of Image Max Side Lengths (Testing Set)')
    plt.xlabel('Max Side Length (pixels)')
    plt.ylabel('Count of Images')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

"""# Unclean : Distribution of Aspect Ratios (Width/Height) - Training Set"""

## Measure aspect ratio distribution for detecting outliers

def get_aspect_ratios(image_list, directory, sample_size=5000, seed=42):
    ratios = []
    if not image_list:
        return ratios

    rng = np.random.default_rng(seed)
    sample_size = min(len(image_list), sample_size)
    sample = rng.choice(image_list, sample_size, replace=False)

    for img_name in tqdm(sample, desc="Calculating Ratios"):
        img_path = os.path.join(directory, img_name)
        img_temp = cv2.imread(img_path)
        if img_temp is not None:
            h, w = img_temp.shape[:2]
            if h > 0:
                ratios.append(w / h)
    return ratios

# Calculate ratios for the training set
train_aspect_ratios = get_aspect_ratios(train_images, train_dir)
df_aspect_train = pd.DataFrame(train_aspect_ratios, columns=['aspect_ratio'])

if df_aspect_train.empty:
    print("No training aspect ratios available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(df_aspect_train['aspect_ratio'], bins=50, kde=True, color='#2196F3')

    mean_ratio = df_aspect_train['aspect_ratio'].mean()
    median_ratio = df_aspect_train['aspect_ratio'].median()

    plt.axvline(mean_ratio, color='red', linestyle='--', label=f'Mean: {mean_ratio:.2f}')
    plt.axvline(median_ratio, color='orange', linestyle='-', label=f'Median: {median_ratio:.2f}')

    plt.title('Distribution of Aspect Ratios (Width/Height) - Training Set')
    plt.xlabel('Aspect Ratio (W/H)')
    plt.ylabel('Count')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

    print(f"--- Aspect Ratio Statistics ---")
    print(df_aspect_train.describe())

"""# Clean : Distribution of Aspect Ratios (Cleaned Training Set)"""

# Calculate IQR for aspect ratio in the training set
if df_aspect_train.empty:
    lower_bound_train = upper_bound_train = np.nan
    outliers_train = df_aspect_train.copy()
    print("No training aspect ratios available for outlier detection.")
else:
    Q1_train = df_aspect_train['aspect_ratio'].quantile(0.25)
    Q3_train = df_aspect_train['aspect_ratio'].quantile(0.75)
    IQR_train = Q3_train - Q1_train

    lower_bound_train = Q1_train - 1.5 * IQR_train
    upper_bound_train = Q3_train + 1.5 * IQR_train

    outliers_train = df_aspect_train[(df_aspect_train['aspect_ratio'] < lower_bound_train) | (df_aspect_train['aspect_ratio'] > upper_bound_train)]

    print(f"--- outlier detection aspect ratio in trainset data ---")
    print(f"Lower Bound: {lower_bound_train:.2f}")
    print(f"Upper Bound: {upper_bound_train:.2f}")
    print(f"Total Outliers found: {len(outliers_train)} out of {len(df_aspect_train)} samples")
    print(f"Percentage of Outliers: {(len(outliers_train)/len(df_aspect_train))*100:.2f}%")

    display(outliers_train.describe())

# Visualize aspect ratio outlier bounds for training data
if df_aspect_train.empty:
    print("No training aspect ratios available to plot.")
else:
    plt.figure(figsize=(12, 4))
    sns.histplot(x=df_aspect_train['aspect_ratio'], color='#2196F3')
    plt.axvline(lower_bound_train, color='red', linestyle='--', label='Lower Bound')
    plt.axvline(upper_bound_train, color='red', linestyle='--', label='Upper Bound')
    plt.title('Aspect Ratios with IQR Outlier Bounds in Training Data')
    plt.legend()
    plt.show()

clean_train_images = []

LOWER_BOUND = lower_bound_train
UPPER_BOUND = upper_bound_train

print(f"Initial training images: {len(train_images)}")

if np.isnan(LOWER_BOUND) or np.isnan(UPPER_BOUND):
    print("Aspect-ratio bounds are not available; keeping all readable training images.")

for img_name in tqdm(train_images, desc="Filtering Training Set"):
    img_path = os.path.join(train_dir, img_name)
    img = cv2.imread(img_path)
    if img is not None:
        h, w = img.shape[:2]
        ratio = w / h

        if np.isnan(LOWER_BOUND) or LOWER_BOUND <= ratio <= UPPER_BOUND:
            clean_train_images.append(img_name)

print("\nFiltering complete.")
print(f"Final Cleaned training images: {len(clean_train_images)}")
print(f"Total images removed: {len(train_images) - len(clean_train_images)}")

# Calculate aspect ratios for the cleaned train dataset
clean_aspect_ratios = []
print("Calculating aspect ratios for cleaned images...")
for img_name in tqdm(clean_train_images):
    img_path = os.path.join(train_dir, img_name)
    img = cv2.imread(img_path)
    if img is not None:
        h, w = img.shape[:2]
        clean_aspect_ratios.append(w / h)

df_clean_aspect = pd.DataFrame(clean_aspect_ratios, columns=['aspect_ratio'])

if df_clean_aspect.empty:
    print("No cleaned training aspect ratios available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(df_clean_aspect['aspect_ratio'], bins=50, kde=True, color='#4CAF50')

    plt.axvline(LOWER_BOUND, color='red', linestyle='--', label=f'Lower Bound: {LOWER_BOUND:.2f}')
    plt.axvline(UPPER_BOUND, color='red', linestyle='--', label=f'Upper Bound: {UPPER_BOUND:.2f}')

    plt.title('Distribution of Aspect Ratios (Cleaned Training Set)')
    plt.xlabel('Aspect Ratio (Width/Height)')
    plt.ylabel('Count')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

    print(f"Summary Statistics for Cleaned Set:")
    print(df_clean_aspect.describe())

"""# Unclean : Distribution of Aspect Ratios (Width/Height) - Testing Set"""

# Calculate aspect ratios for the testing set
test_aspect_ratios = get_aspect_ratios(test_images, test_dir)
df_aspect_test = pd.DataFrame(test_aspect_ratios, columns=['aspect_ratio'])

if df_aspect_test.empty:
    print("No testing aspect ratios available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(df_aspect_test['aspect_ratio'], bins=50, kde=True, color='#2196F3')

    mean_ratio = df_aspect_test['aspect_ratio'].mean()
    median_ratio = df_aspect_test['aspect_ratio'].median()

    plt.axvline(mean_ratio, color='red', linestyle='--', label=f'Mean: {mean_ratio:.2f}')
    plt.axvline(median_ratio, color='orange', linestyle='-', label=f'Median: {median_ratio:.2f}')

    plt.title('Distribution of Aspect Ratios (Width/Height) - Testing Data')
    plt.xlabel('Aspect Ratio (W/H)')
    plt.ylabel('Count')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

    print(f"--- Aspect Ratio Statistics ---")
    print(df_aspect_test.describe())

"""#Clean : Distribution of Aspect Ratios (Width/Height) - Testing Set"""

# Calculate IQR for aspect ratio in testset data
if df_aspect_test.empty:
    lower_bound_test = upper_bound_test = np.nan
    outliers_test = df_aspect_test.copy()
    print("No testing aspect ratios available for outlier detection.")
else:
    Q1_test = df_aspect_test['aspect_ratio'].quantile(0.25)
    Q3_test = df_aspect_test['aspect_ratio'].quantile(0.75)
    IQR_test = Q3_test - Q1_test

    lower_bound_test = Q1_test - 1.5 * IQR_test
    upper_bound_test = Q3_test + 1.5 * IQR_test

    outliers_test = df_aspect_test[(df_aspect_test['aspect_ratio'] < lower_bound_test) | (df_aspect_test['aspect_ratio'] > upper_bound_test)]

    print(f"--- outlier detection in testset data ---")
    print(f"Lower Bound: {lower_bound_test:.2f}")
    print(f"Upper Bound: {upper_bound_test:.2f}")
    print(f"Total Outliers found: {len(outliers_test)} out of {len(df_aspect_test)} samples")
    print(f"Percentage of Outliers: {(len(outliers_test)/len(df_aspect_test))*100:.2f}%")

    display(outliers_test.describe())

# Visualize aspect ratio outlier bounds for testing data
if df_aspect_test.empty:
    print("No testing aspect ratios available to plot.")
else:
    plt.figure(figsize=(12, 4))
    sns.histplot(x=df_aspect_test['aspect_ratio'], color='#2196F3')
    plt.axvline(lower_bound_test, color='red', linestyle='--', label='Lower Bound')
    plt.axvline(upper_bound_test, color='red', linestyle='--', label='Upper Bound')
    plt.title('Aspect Ratios with IQR Outlier Bounds in Testing Data')
    plt.legend()
    plt.show()

clean_test_images = []
LOWER_BOUND_TEST = lower_bound_test
UPPER_BOUND_TEST = upper_bound_test

print(f"Initial testing images: {len(test_images)}")

if np.isnan(LOWER_BOUND_TEST) or np.isnan(UPPER_BOUND_TEST):
    print("Aspect-ratio bounds are not available; keeping all readable testing images.")

for img_name in tqdm(test_images, desc="Filtering Testing Set"):
    img_path = os.path.join(test_dir, img_name)
    img = cv2.imread(img_path)
    if img is not None:
        h, w = img.shape[:2]
        ratio = w / h
        if np.isnan(LOWER_BOUND_TEST) or LOWER_BOUND_TEST <= ratio <= UPPER_BOUND_TEST:
            clean_test_images.append(img_name)

print("\nFiltering complete.")
print(f"Final Cleaned testing images: {len(clean_test_images)}")
print(f"Total images removed: {len(test_images) - len(clean_test_images)}")

# Calculate mean brightness for training images
if 'train_images' not in locals():
    train_images = list_images(train_dir)

brightness_values_train = []

print(f"Calculating brightness for {len(train_images)} training images...")
for img_name in tqdm(train_images):
    img_path = os.path.join(train_dir, img_name)
    temp_img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if temp_img is not None:
        brightness_values_train.append(np.mean(temp_img))

brightness_values_train = np.array(brightness_values_train)

# Calculate mean brightness for testing images
if 'test_images' not in locals():
    test_images = list_images(test_dir)

brightness_values_test = []

print(f"Calculating brightness for {len(test_images)} testing images...")
for img_name in tqdm(test_images):
    img_path = os.path.join(test_dir, img_name)
    temp_img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if temp_img is not None:
        brightness_values_test.append(np.mean(temp_img))

brightness_values_test = np.array(brightness_values_test)

# Calculate aspect ratios for the cleaned test dataset
clean_aspect_ratios_test = []
for img_name in tqdm(clean_test_images, desc="Final Scan"):
    img_path = os.path.join(test_dir, img_name)
    img = cv2.imread(img_path)
    if img is not None:
        h, w = img.shape[:2]
        clean_aspect_ratios_test.append(w / h)

df_clean_aspect_test = pd.DataFrame(clean_aspect_ratios_test, columns=['aspect_ratio'])

if df_clean_aspect_test.empty:
    print("No cleaned testing aspect ratios available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(df_clean_aspect_test['aspect_ratio'], bins=50, kde=True, color='#4CAF50')
    plt.axvline(LOWER_BOUND_TEST, color='red', linestyle='--', label=f'Lower Bound: {LOWER_BOUND_TEST:.2f}')
    plt.axvline(UPPER_BOUND_TEST, color='red', linestyle='--', label=f'Upper Bound: {UPPER_BOUND_TEST:.2f}')
    plt.title('Distribution of Aspect Ratios (Cleaned Testing Set)')
    plt.xlabel('Aspect Ratio (Width/Height)')
    plt.ylabel('Count')
    plt.legend()
    plt.show()

"""# Clean : Distribution of Mean Brightness - Training Set"""

## Brightness (mean) distribution - training data
if len(brightness_values_train) == 0:
    print("No training brightness values available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(brightness_values_train, bins=50, kde=True, color='#FFC107')

    mean_b_train = np.mean(brightness_values_train)
    std_b_train = np.std(brightness_values_train)
    median_b_train = np.median(brightness_values_train)

    plt.axvline(mean_b_train, color='red', linestyle='--', label=f'Mean: {mean_b_train:.2f}')
    plt.axvline(median_b_train, color='green', linestyle='--', label=f'Median: {median_b_train:.2f}')
    plt.axvline(mean_b_train - 2*std_b_train, color='blue', linestyle=':', label='2 Std Dev (Lower)')
    plt.axvline(mean_b_train + 2*std_b_train, color='blue', linestyle=':', label='2 Std Dev (Upper)')

    plt.title('Distribution of Mean Brightness - Training Set')
    plt.xlabel('Mean Pixel Intensity (0-255)')
    plt.ylabel('Count of Images')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

    print(f"--- Brightness Statistics ---")
    print(f"Average Brightness: {mean_b_train:.2f}")
    print(f"Median Brightness: {median_b_train:.2f}")
    print(f"Standard Deviation: {std_b_train:.2f}")
    print(f"Min Brightness:     {np.min(brightness_values_train):.2f}")
    print(f"Max Brightness:     {np.max(brightness_values_train):.2f}")

"""# Distribution of Mean Brightness - Testing Set"""

## Brightness (mean) distribution - testing data
if len(brightness_values_test) == 0:
    print("No testing brightness values available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(brightness_values_test, bins=50, kde=True, color='#FFC107')

    mean_b_test = np.mean(brightness_values_test)
    std_b_test = np.std(brightness_values_test)
    median_b_test = np.median(brightness_values_test)

    plt.axvline(mean_b_test, color='red', linestyle='--', label=f'Mean: {mean_b_test:.2f}')
    plt.axvline(median_b_test, color='green', linestyle='--', label=f'Median: {median_b_test:.2f}')
    plt.axvline(mean_b_test - 2*std_b_test, color='blue', linestyle=':', label='2 Std Dev (Lower)')
    plt.axvline(mean_b_test + 2*std_b_test, color='blue', linestyle=':', label='2 Std Dev (Upper)')

    plt.title('Distribution of Mean Brightness - Testing Set')
    plt.xlabel('Mean Pixel Intensity (0-255)')
    plt.ylabel('Count of Images')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

    print(f"--- Brightness Statistics ---")
    print(f"Average Brightness: {mean_b_test:.2f}")
    print(f"Median Brightness: {median_b_test:.2f}")
    print(f"Standard Deviation: {std_b_test:.2f}")
    print(f"Min Brightness:     {np.min(brightness_values_test):.2f}")
    print(f"Max Brightness:     {np.max(brightness_values_test):.2f}")

"""# Unclean : Distribution of Image Sharpness (Laplacian Variance) - Training Set"""

## Sharpness distribution for detecting outliers - training data
sharpness_values_train = []

print(f"Calculating sharpness for {len(train_images)} images...")
for img_name in tqdm(train_images):
    img_path = os.path.join(train_dir, img_name)
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is not None:
        score = cv2.Laplacian(img, cv2.CV_64F).var()
        sharpness_values_train.append(score)

sharpness_values_train = np.array(sharpness_values_train)
df_sharpness_train = pd.DataFrame(sharpness_values_train, columns=['laplacian_var'])

# Training sharpness distribution
if df_sharpness_train.empty:
    print("No training sharpness values available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(df_sharpness_train['laplacian_var'], bins=100, kde=True, color='#9C27B0')

    SHARPNESS_THRESHOLD_TRAIN = np.percentile(sharpness_values_train, 5)

    plt.axvline(SHARPNESS_THRESHOLD_TRAIN, color='red', linestyle='--', label=f'5th Percentile (Blurry): {SHARPNESS_THRESHOLD_TRAIN:.2f}')
    plt.title('Unclean : Distribution of Image Sharpness (Laplacian Variance) - Training Set')
    plt.xlabel('Laplacian Variance (Higher = Sharper)')
    plt.ylabel('Count')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.yscale('log')
    plt.show()

    print(f"--- Sharpness Statistics ---")
    print(df_sharpness_train.describe())

"""# Clean : Distribution of Image Sharpness (Laplacian Variance) - Training Set"""

# Clean Distribution of Image Sharpness (Laplacian Variance) - Training Set
final_clean_train_images = []
SHARPNESS_THRESHOLD_TRAIN = np.percentile(sharpness_values_train, 5) if len(sharpness_values_train) else 0

print(f"Current cleaned images (after aspect ratio filter): {len(clean_train_images)}")

for img_name in tqdm(clean_train_images, desc="Sharpness Filtering"):
    img_path = os.path.join(train_dir, img_name)
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

    if img is not None:
        score = cv2.Laplacian(img, cv2.CV_64F).var()
        if score >= SHARPNESS_THRESHOLD_TRAIN:
            final_clean_train_images.append(img_name)

print("\nFiltering complete.")
print(f"Final Training Dataset Size: {len(final_clean_train_images)}")
print(f"Removed {len(clean_train_images) - len(final_clean_train_images)} blurry images.")

# Calculate sharpness for the final cleaned training dataset
final_sharpness_values = []
print("Calculating sharpness for final cleaned images...")
for img_name in tqdm(final_clean_train_images):
    img_path = os.path.join(train_dir, img_name)
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is not None:
        score = cv2.Laplacian(img, cv2.CV_64F).var()
        final_sharpness_values.append(score)

if len(final_sharpness_values) == 0:
    print("No final cleaned training sharpness values available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(final_sharpness_values, bins=100, kde=True, color='#9C27B0')

    plt.axvline(SHARPNESS_THRESHOLD_TRAIN, color='red', linestyle='--', label=f'Threshold: {SHARPNESS_THRESHOLD_TRAIN:.2f}')

    plt.title('Clean : Distribution of Image Sharpness (Final Cleaned Training Set)')
    plt.xlabel('Laplacian Variance (Higher = Sharper)')
    plt.ylabel('Count')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.yscale('log')
    plt.show()

    print(f"--- Final Sharpness Statistics ---")
    print(pd.Series(final_sharpness_values).describe())

"""# Unclean : Distribution of Image Sharpness (Laplacian Variance) - Testing Set"""

# unclean : sharpness distribution for detecting outlier
sharpness_values_test = []

print(f"Calculating sharpness for {len(test_images)} images...")
for img_name in tqdm(test_images):
    img_path = os.path.join(test_dir, img_name)
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is not None:
        # Compute the Laplacian and then the variance
        score = cv2.Laplacian(img, cv2.CV_64F).var()
        sharpness_values_test.append(score)

sharpness_values_test = np.array(sharpness_values_test)
df_sharpness_test = pd.DataFrame(sharpness_values_test, columns=['laplacian_var'])

# Unclean sharpness distribution in testing set
if df_sharpness_test.empty:
    print("No testing sharpness values available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(df_sharpness_test['laplacian_var'], bins=100, kde=True, color='#9C27B0')

    SHARPNESS_THRESHOLD_TEST = np.percentile(sharpness_values_test, 5)

    plt.axvline(SHARPNESS_THRESHOLD_TEST, color='red', linestyle='--', label=f'5th Percentile (Blurry): {SHARPNESS_THRESHOLD_TEST:.2f}')
    plt.title('Unclean : Distribution of Image Sharpness (Laplacian Variance) - Testing Set')
    plt.xlabel('Laplacian Variance (Higher = Sharper)')
    plt.ylabel('Count')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.yscale('log')
    plt.show()

    print(f"--- Sharpness Statistics ---")
    print(df_sharpness_test.describe())

"""# Clean : Distribution of Image Sharpness (Laplacian Variance) - Testing Set"""

# Clean distribution of image sharpness - testing set
final_clean_test_images = []
SHARPNESS_THRESHOLD_TEST = np.percentile(sharpness_values_test, 5) if len(sharpness_values_test) else 0

print(f"Current cleaned images (after aspect ratio filter): {len(clean_test_images)}")

for img_name in tqdm(clean_test_images, desc="Sharpness Filtering"):
    img_path = os.path.join(test_dir, img_name)
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

    if img is not None:
        score = cv2.Laplacian(img, cv2.CV_64F).var()
        if score >= SHARPNESS_THRESHOLD_TEST:
            final_clean_test_images.append(img_name)

print("\nFiltering complete.")
print(f"Final Testing Dataset Size: {len(final_clean_test_images)}")
print(f"Removed {len(clean_test_images) - len(final_clean_test_images)} blurry images.")

# Calculate sharpness for the final cleaned testing dataset
final_sharpness_values_test = []
print("Calculating sharpness for final cleaned images...")
for img_name in tqdm(final_clean_test_images):
    img_path = os.path.join(test_dir, img_name)
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    if img is not None:
        score = cv2.Laplacian(img, cv2.CV_64F).var()
        final_sharpness_values_test.append(score)

if len(final_sharpness_values_test) == 0:
    print("No final cleaned testing sharpness values available to plot.")
else:
    plt.figure(figsize=(12, 6))
    sns.histplot(final_sharpness_values_test, bins=100, kde=True, color='#9C27B0')

    plt.axvline(SHARPNESS_THRESHOLD_TEST, color='red', linestyle='--', label=f'Threshold: {SHARPNESS_THRESHOLD_TEST:.2f}')

    plt.title('Clean : Distribution of Image Sharpness (Final Cleaned Testing Set)')
    plt.xlabel('Laplacian Variance (Higher = Sharper)')
    plt.ylabel('Count')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.yscale('log')
    plt.show()

    print(f"--- Final Sharpness Statistics ---")
    print(pd.Series(final_sharpness_values_test).describe())

"""# Clean : Summary the Data"""

summary_data = {
    'Dataset': ['Training Set', 'Testing Set'],
    'Original Size': [len(train_images), len(test_images)],
    'Cleaned Size': [len(final_clean_train_images), len(final_clean_test_images)],
    'Removed Count': [len(train_images) - len(final_clean_train_images), len(test_images) - len(final_clean_test_images)]
}

df_summary = pd.DataFrame(summary_data)
df_summary['% Retention'] = np.where(
    df_summary['Original Size'] > 0,
    (df_summary['Cleaned Size'] / df_summary['Original Size'] * 100).round(2),
    0,
)

display(df_summary)

print("Next Step: Step 2 - Image Resizing & Letterboxing (Padding)")

"""# Image Resizing with Letterboxing (Padding)"""

def letterbox_image(image, size=(224, 224)):
    """Resize an RGB image with gray padding while preserving aspect ratio."""
    if image is None:
        raise ValueError("letterbox_image received None instead of an image array")

    ih, iw = image.shape[:2]
    w, h = size
    scale = min(w / iw, h / ih)
    nw = max(1, int(iw * scale))
    nh = max(1, int(ih * scale))

    image_resized = cv2.resize(image, (nw, nh), interpolation=cv2.INTER_AREA)

    if image.ndim == 2:
        new_image = np.full((h, w), 128, dtype=np.uint8)
        top = (h - nh) // 2
        left = (w - nw) // 2
        new_image[top:top+nh, left:left+nw] = image_resized
    else:
        channels = image.shape[2]
        new_image = np.full((h, w, channels), 128, dtype=np.uint8)
        top = (h - nh) // 2
        left = (w - nw) // 2
        new_image[top:top+nh, left:left+nw, :] = image_resized

    return new_image

# --- Demo of Resizing ---
if not final_clean_train_images:
    print("No cleaned training images available for the letterbox demo.")
else:
    sample_path = os.path.join(train_dir, final_clean_train_images[0])
    original_img = cv2.imread(sample_path)

    if original_img is None:
        print(f"Failed to load image: {sample_path}")
    else:
        original_img_rgb = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)
        resized_img = letterbox_image(original_img_rgb, (224, 224))

        fig, axes = plt.subplots(1, 2, figsize=(12, 5))
        axes[0].imshow(original_img_rgb)
        axes[0].set_title(f"Original: {original_img.shape[1]}x{original_img.shape[0]}")
        axes[0].axis('off')

        axes[1].imshow(resized_img)
        axes[1].set_title("Letterboxed: 224x224")
        axes[1].axis('off')

        plt.tight_layout()
        plt.show()

"""# Label Encoding Sample
To train a classifier, we need to convert the vehicle IDs in the filenames into integer labels.
In VeRi, the filename format is `VehicleID_CameraID_SequenceID_ImageID.jpg`.
"""

# start label Encoding
def extract_ids(image_list):
    # Filenames are like '0064_c017_00032145_0.jpg', the ID is the first part
    return [img_name.split('_')[0] for img_name in image_list]

# Extract raw IDs
train_ids_raw = extract_ids(final_clean_train_images)
test_ids_raw = extract_ids(final_clean_test_images)

# Create a mapping from unique ID string to an integer index
unique_train_ids = sorted(list(set(train_ids_raw)))
id_to_idx = {id_str: i for i, id_str in enumerate(unique_train_ids)}

# Map the IDs to integers
train_labels = [id_to_idx[id_str] for id_str in train_ids_raw]

print(f"Number of unique vehicles in Training Set: {len(unique_train_ids)}")
print(f"Sample Mapping: {list(id_to_idx.items())[:5]}")
print(f"First 5 training labels: {train_labels[:5]}")

"""# Dataset Loading
We will now wrap our cleaned image lists and labels into a PyTorch Dataset. This class will handle loading images from disk and applying the `letterbox_image` transformation (resizing and padding) to every image automatically.
"""

import torch
from torch.utils.data import Dataset, DataLoader

class VeRiDataset(Dataset):
    def __init__(self, image_list, labels, directory, size=(224, 224)):
        if len(image_list) != len(labels):
            raise ValueError(f"image_list and labels must have the same length, got {len(image_list)} and {len(labels)}")
        self.image_list = image_list
        self.labels = labels
        self.directory = directory
        self.size = size

    def __len__(self):
        return len(self.image_list)

    def __getitem__(self, idx):
        img_name = self.image_list[idx]
        label = self.labels[idx]
        img_path = os.path.join(self.directory, img_name)

        image = cv2.imread(img_path)
        if image is None:
            raise FileNotFoundError(f"Could not read image: {img_path}")
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        image = letterbox_image(image, size=self.size)

        image = image.astype(np.float32) / 255.0
        image = np.transpose(image, (2, 0, 1))

        return torch.from_numpy(image), torch.tensor(label, dtype=torch.long)

# Initialize the Training Dataset
train_dataset = VeRiDataset(final_clean_train_images, train_labels, train_dir)

# Create a DataLoader to iterate through all pictures in batches of 32
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

print(f"Successfully created a pipeline for {len(train_dataset)} training images.")

# Verification: check one batch from the loader
if len(train_dataset) == 0:
    print("Training dataset is empty; no batch is available.")
else:
    images, batch_labels = next(iter(train_loader))
    print(f"Batch Image Tensor Shape: {images.shape}")  # [batch_size, 3, 224, 224]
    print(f"Batch Label Tensor Shape: {batch_labels.shape}")

"""### Verification: Visualizing Multiple Letterboxed Images
Let's pick 3 random images to verify that the resizing and padding are applied correctly to different vehicle shapes.
"""

import random

if not final_clean_train_images:
    print("No cleaned training images available to visualize.")
else:
    n_samples = min(3, len(final_clean_train_images))
    indices = random.sample(range(len(final_clean_train_images)), n_samples)

    fig, axes = plt.subplots(1, n_samples, figsize=(5 * n_samples, 5))
    if n_samples == 1:
        axes = [axes]

    for i, idx in enumerate(indices):
        img_name = final_clean_train_images[idx]
        img_path = os.path.join(train_dir, img_name)

        img = cv2.imread(img_path)
        if img is None:
            axes[i].set_title(f"Failed: {img_name}")
            axes[i].axis('off')
            continue

        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        processed_img = letterbox_image(img_rgb, (224, 224))

        axes[i].imshow(processed_img)
        axes[i].set_title(f"Image {i+1}: {img_name}")
        axes[i].axis('off')

    plt.tight_layout()
    plt.show()

# Ensure we are using the CLEANED data from Step 4
img_hsv = None
img_lab = None

if 'final_clean_train_images' in locals() and len(final_clean_train_images) > 0:
    print(f"Using cleaned dataset: {len(final_clean_train_images)} images available (outliers removed).")

    sample_img_name = final_clean_train_images[0]
    sample_img_path = os.path.join(train_dir, sample_img_name)

    img_bgr = cv2.imread(sample_img_path)

    if img_bgr is not None:
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)
        img_lab = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2Lab)

        fig, axes = plt.subplots(1, 3, figsize=(18, 6))
        axes[0].imshow(img_rgb)
        axes[0].set_title(f"Cleaned Image (RGB)\n{sample_img_name}")
        axes[0].axis('off')

        axes[1].imshow(img_hsv)
        axes[1].set_title("HSV Space (Lighting Robust)")
        axes[1].axis('off')

        axes[2].imshow(img_lab)
        axes[2].set_title("Lab Space (Perceptual)")
        axes[2].axis('off')

        plt.tight_layout()
        plt.show()
    else:
        print(f"Failed to load image: {sample_img_path}")
else:
    print("Error: The cleaned image list 'final_clean_train_images' is not available.")
    print("Please make sure to run the filtering cells first.")

"""### Comparison: Why use HSV or Lab instead of RGB?

| Color Space | Key Benefit | Best Use Case |
| :--- | :--- | :--- |
| **RGB** | Standard format for cameras/displays. | General deep learning input. |
| **HSV** | Separates color (Hue) from brightness (Value). | Handling shadows, lighting changes, and color-based tracking. |
| **Lab** | Perceptually uniform (mimics human eye). | Accurate color comparison and skin/surface detection. |
"""

# Comparison: Why use HSV or Lab instead of RGB?
# Visualizing individual channels to show separation of information
if img_hsv is None or img_lab is None:
    print("HSV/Lab images are not available. Run the previous cell successfully first.")
else:
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))

    axes[0, 0].imshow(img_hsv[:, :, 0], cmap='hsv')
    axes[0, 0].set_title("HSV: Hue (Pure Color)")
    axes[0, 1].imshow(img_hsv[:, :, 1], cmap='gray')
    axes[0, 1].set_title("HSV: Saturation (Intensity)")
    axes[0, 2].imshow(img_hsv[:, :, 2], cmap='gray')
    axes[0, 2].set_title("HSV: Value (Brightness/Shadows)")

    axes[1, 0].imshow(img_lab[:, :, 0], cmap='gray')
    axes[1, 0].set_title("Lab: L (Lightness)")
    axes[1, 1].imshow(img_lab[:, :, 1], cmap='RdYlGn_r')
    axes[1, 1].set_title("Lab: a (Green-Red axis)")
    axes[1, 2].imshow(img_lab[:, :, 2], cmap='YlGnBu_r')
    axes[1, 2].set_title("Lab: b (Blue-Yellow axis)")

    for ax_row in axes:
        for ax in ax_row:
            ax.axis('off')

    plt.tight_layout()
    plt.show()

"""# Computer Vision Next Steps

This section adds reusable OpenCV utilities for drawing, coordinate handling, image enhancement, outlier filtering, camera/video loops, smoothing, edge detection, feature matching, homography, blending, HDR-style exposure merging, centroid tracking, Kalman prediction, and optical flow.
"""

# Shared helpers for the computer-vision demos
import math
import sys
from collections import OrderedDict


def get_demo_image():
    """Load a cleaned training image when available, otherwise return a synthetic demo image."""
    if 'final_clean_train_images' in globals() and final_clean_train_images:
        img_path = os.path.join(train_dir, final_clean_train_images[0])
        img_bgr = cv2.imread(img_path)
        if img_bgr is not None:
            return cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB), img_path

    demo = np.full((360, 640, 3), 35, dtype=np.uint8)
    cv2.rectangle(demo, (120, 90), (500, 280), (45, 130, 210), -1)
    cv2.circle(demo, (320, 185), 65, (230, 230, 80), -1)
    cv2.putText(demo, 'DEMO', (250, 200), cv2.FONT_HERSHEY_SIMPLEX, 1.2, (10, 10, 10), 3, cv2.LINE_AA)
    return demo, 'synthetic_demo'


def show_rgb(image, title='', figsize=(8, 5)):
    plt.figure(figsize=figsize)
    plt.imshow(image)
    plt.title(title)
    plt.axis('off')
    plt.show()


def to_gray(image_rgb):
    return cv2.cvtColor(image_rgb, cv2.COLOR_RGB2GRAY)


def safe_imshow(window_name, frame_bgr):
    """Use cv2.imshow only in local desktop Python, not in headless/Colab sessions."""
    if 'google.colab' in sys.modules:
        return False
    try:
        cv2.imshow(window_name, frame_bgr)
        return True
    except cv2.error:
        return False

sample_rgb, sample_source = get_demo_image()
print(f"Demo image source: {sample_source}")
print(f"Demo image shape: {sample_rgb.shape}  # height, width, channels")
show_rgb(sample_rgb, 'Demo Image')

"""## 1-2. Drawing Overlays and Coordinate Mapping

OpenCV uses pixel coordinates as `(x, y)`, where `x` moves left-to-right across columns and `y` moves top-to-bottom across rows. Image arrays are indexed as `image[y, x]`, so helper functions should make that conversion explicit.
"""

def clamp_point(x, y, width, height):
    x = int(np.clip(round(x), 0, width - 1))
    y = int(np.clip(round(y), 0, height - 1))
    return x, y


def normalized_to_pixel(x_norm, y_norm, image_shape):
    height, width = image_shape[:2]
    return clamp_point(x_norm * (width - 1), y_norm * (height - 1), width, height)


def draw_annotations(image_rgb, boxes=None, points=None, label='vehicle'):
    annotated = image_rgb.copy()
    height, width = annotated.shape[:2]

    if boxes is None:
        boxes = [(0.15, 0.20, 0.80, 0.78)]  # normalized x1, y1, x2, y2
    if points is None:
        points = [(0.50, 0.50), (0.25, 0.35), (0.75, 0.65)]

    for i, (x1n, y1n, x2n, y2n) in enumerate(boxes):
        x1, y1 = normalized_to_pixel(x1n, y1n, annotated.shape)
        x2, y2 = normalized_to_pixel(x2n, y2n, annotated.shape)
        cv2.rectangle(annotated, (x1, y1), (x2, y2), (0, 255, 0), 3)
        cv2.putText(annotated, f'{label}_{i}', (x1, max(20, y1 - 10)), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2, cv2.LINE_AA)

    for x_norm, y_norm in points:
        x, y = normalized_to_pixel(x_norm, y_norm, annotated.shape)
        cv2.circle(annotated, (x, y), 7, (255, 80, 80), -1)
        cv2.putText(annotated, f'({x},{y})', (x + 10, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 0), 1, cv2.LINE_AA)

    cv2.line(annotated, (0, height // 2), (width - 1, height // 2), (255, 200, 0), 2)
    return annotated

annotated_rgb = draw_annotations(sample_rgb)
show_rgb(annotated_rgb, 'Drawing: Boxes, Points, Text, and Pixel Coordinates')

"""## 3-4. Brightness, Contrast, Histogram Equalization, and IQR Outlier Removal

Use linear intensity transforms for simple brightness/contrast. Use histogram equalization on luminance only, not independently on RGB channels, to avoid unnatural color shifts.
"""

def adjust_brightness_contrast(image_rgb, alpha=1.2, beta=15):
    """alpha controls contrast; beta controls brightness."""
    return cv2.convertScaleAbs(image_rgb, alpha=alpha, beta=beta)


def equalize_luminance(image_rgb, method='clahe'):
    lab = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2LAB)
    l_channel, a_channel, b_channel = cv2.split(lab)

    if method == 'clahe':
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        l_equalized = clahe.apply(l_channel)
    else:
        l_equalized = cv2.equalizeHist(l_channel)

    lab_equalized = cv2.merge((l_equalized, a_channel, b_channel))
    return cv2.cvtColor(lab_equalized, cv2.COLOR_LAB2RGB)


def iqr_bounds(values, multiplier=1.5):
    values = np.asarray(values, dtype=np.float32)
    if values.size == 0:
        return np.nan, np.nan
    q1 = np.percentile(values, 25)
    q3 = np.percentile(values, 75)
    iqr = q3 - q1
    return q1 - multiplier * iqr, q3 + multiplier * iqr


def remove_iqr_outliers(df, column, multiplier=1.5):
    lower, upper = iqr_bounds(df[column].dropna().to_numpy(), multiplier=multiplier)
    if np.isnan(lower) or np.isnan(upper):
        return df.copy(), lower, upper
    mask = df[column].between(lower, upper, inclusive='both')
    return df.loc[mask].copy(), lower, upper

bright_contrast_rgb = adjust_brightness_contrast(sample_rgb, alpha=1.25, beta=20)
equalized_rgb = equalize_luminance(sample_rgb, method='clahe')

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
for ax, img, title in zip(axes, [sample_rgb, bright_contrast_rgb, equalized_rgb], ['Original', 'Brightness/Contrast', 'CLAHE on Luminance']):
    ax.imshow(img)
    ax.set_title(title)
    ax.axis('off')
plt.tight_layout()
plt.show()

if 'df_dist' in globals() and not df_dist.empty:
    df_dist_clean, lower_max_side, upper_max_side = remove_iqr_outliers(df_dist, 'max_side')
    print(f"Max-side IQR bounds: {lower_max_side:.2f} to {upper_max_side:.2f}")
    print(f"Removed max-side outliers: {len(df_dist) - len(df_dist_clean)} / {len(df_dist)}")
else:
    print('df_dist is not available yet. Run the image-dimension cells before using IQR outlier removal on dataset metrics.')

"""## 5-6. Video Capture and a Real-Time While Loop

Camera loops should always check `cap.isOpened()`, break cleanly, and release hardware in `finally`. Use `CAP_PROP_FPS` as a request, not a guarantee; actual FPS depends on hardware and processing time.
"""

def make_jetson_gstreamer_pipeline(sensor_id=0, capture_width=1280, capture_height=720, display_width=640, display_height=360, framerate=30, flip_method=0):
    return (
        f'nvarguscamerasrc sensor-id={sensor_id} ! '
        f'video/x-raw(memory:NVMM), width=(int){capture_width}, height=(int){capture_height}, framerate=(fraction){framerate}/1 ! '
        f'nvvidconv flip-method={flip_method} ! '
        f'video/x-raw, width=(int){display_width}, height=(int){display_height}, format=(string)BGRx ! '
        'videoconvert ! video/x-raw, format=(string)BGR ! appsink'
    )


def open_video_capture(source=0, width=640, height=480, fps=30, use_jetson_csi=False):
    if use_jetson_csi:
        source = make_jetson_gstreamer_pipeline(display_width=width, display_height=height, framerate=fps)
        cap = cv2.VideoCapture(source, cv2.CAP_GSTREAMER)
    else:
        cap = cv2.VideoCapture(source)

    cap.set(cv2.CAP_PROP_FRAME_WIDTH, width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, height)
    cap.set(cv2.CAP_PROP_FPS, fps)
    return cap


def process_frame(frame_bgr):
    gray = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 80, 160)
    overlay = frame_bgr.copy()
    overlay[edges > 0] = (0, 255, 255)
    return overlay


def run_camera_loop(source=0, width=640, height=480, fps=30, max_frames=None, use_jetson_csi=False):
    cap = open_video_capture(source, width, height, fps, use_jetson_csi=use_jetson_csi)
    if not cap.isOpened():
        print('Camera/video source could not be opened. Check permissions, index, path, or Jetson pipeline.')
        return

    frame_count = 0
    try:
        while True:
            ok, frame = cap.read()
            if not ok:
                print('Frame grab failed or stream ended.')
                break

            processed = process_frame(frame)
            if not safe_imshow('Processed Frame', processed):
                print('Display window is unavailable in this environment; stopping after one processed frame.')
                break

            frame_count += 1
            if max_frames is not None and frame_count >= max_frames:
                break
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
    finally:
        cap.release()
        cv2.destroyAllWindows()

print('Camera loop utilities are defined. Locally, call run_camera_loop(source=0). On Jetson CSI, use use_jetson_csi=True.')

"""## 7-8. Blurring, Low-Sharpness Removal, and Canny Edge Detection

Gaussian blur is a good default for sensor noise. Median blur is useful for salt-and-pepper noise. For blur filtering, removing the bottom 5% by Laplacian variance is a defensible starting point.
"""

def gaussian_blur(image_rgb, kernel_size=5, sigma=0):
    kernel_size = kernel_size if kernel_size % 2 == 1 else kernel_size + 1
    return cv2.GaussianBlur(image_rgb, (kernel_size, kernel_size), sigma)


def median_blur(image_rgb, kernel_size=5):
    kernel_size = kernel_size if kernel_size % 2 == 1 else kernel_size + 1
    return cv2.medianBlur(image_rgb, kernel_size)


def laplacian_sharpness(image_rgb):
    return cv2.Laplacian(to_gray(image_rgb), cv2.CV_64F).var()


def remove_low_sharpness_outliers(image_names, directory, percentile=5):
    scores = []
    readable_names = []
    for name in tqdm(image_names, desc='Scoring sharpness'):
        img_bgr = cv2.imread(os.path.join(directory, name))
        if img_bgr is None:
            continue
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        scores.append(laplacian_sharpness(img_rgb))
        readable_names.append(name)

    if not scores:
        return [], np.nan, pd.DataFrame(columns=['image', 'sharpness'])

    threshold = np.percentile(scores, percentile)
    df_scores = pd.DataFrame({'image': readable_names, 'sharpness': scores})
    kept = df_scores.loc[df_scores['sharpness'] >= threshold, 'image'].tolist()
    return kept, threshold, df_scores


def canny_edges(image_rgb, low_threshold=80, high_threshold=160, blur_kernel=5):
    gray = to_gray(image_rgb)
    if blur_kernel and blur_kernel > 1:
        gray = cv2.GaussianBlur(gray, (blur_kernel, blur_kernel), 0)
    return cv2.Canny(gray, low_threshold, high_threshold)

blurred_rgb = gaussian_blur(sample_rgb, kernel_size=5)
median_rgb = median_blur(sample_rgb, kernel_size=5)
edges = canny_edges(sample_rgb)

fig, axes = plt.subplots(1, 4, figsize=(18, 5))
axes[0].imshow(sample_rgb); axes[0].set_title('Original')
axes[1].imshow(blurred_rgb); axes[1].set_title('Gaussian Blur')
axes[2].imshow(median_rgb); axes[2].set_title('Median Blur')
axes[3].imshow(edges, cmap='gray'); axes[3].set_title('Canny Edges')
for ax in axes:
    ax.axis('off')
plt.tight_layout()
plt.show()

print(f"Sample Laplacian sharpness: {laplacian_sharpness(sample_rgb):.2f}")

"""## 9-11. Feature Matching, Homography, and Blending

Use ORB when you need a fast, patent-free baseline. Use SIFT when available and accuracy matters more than speed. Estimate homography with RANSAC so bad matches do not dominate the transform.
"""

def create_feature_detector(method='ORB', max_features=2000):
    method = method.upper()
    if method == 'SIFT' and hasattr(cv2, 'SIFT_create'):
        return cv2.SIFT_create(nfeatures=max_features), cv2.NORM_L2
    return cv2.ORB_create(nfeatures=max_features), cv2.NORM_HAMMING


def match_features(image_a_rgb, image_b_rgb, method='ORB', ratio=0.75, max_features=2000):
    detector, norm_type = create_feature_detector(method, max_features=max_features)
    gray_a = to_gray(image_a_rgb)
    gray_b = to_gray(image_b_rgb)
    kp_a, desc_a = detector.detectAndCompute(gray_a, None)
    kp_b, desc_b = detector.detectAndCompute(gray_b, None)

    if desc_a is None or desc_b is None or len(kp_a) < 4 or len(kp_b) < 4:
        return kp_a, kp_b, []

    matcher = cv2.BFMatcher(norm_type)
    knn = matcher.knnMatch(desc_a, desc_b, k=2)
    good = []
    for pair in knn:
        if len(pair) == 2:
            m, n = pair
            if m.distance < ratio * n.distance:
                good.append(m)
    return kp_a, kp_b, good


def estimate_homography(kp_a, kp_b, matches, reproj_threshold=4.0):
    if len(matches) < 4:
        return None, None
    pts_a = np.float32([kp_a[m.queryIdx].pt for m in matches]).reshape(-1, 1, 2)
    pts_b = np.float32([kp_b[m.trainIdx].pt for m in matches]).reshape(-1, 1, 2)
    H, mask = cv2.findHomography(pts_a, pts_b, cv2.RANSAC, reproj_threshold)
    return H, mask


def alpha_blend(image_a_rgb, image_b_rgb, alpha=0.5):
    if image_a_rgb.shape != image_b_rgb.shape:
        image_b_rgb = cv2.resize(image_b_rgb, (image_a_rgb.shape[1], image_a_rgb.shape[0]))
    return cv2.addWeighted(image_a_rgb, alpha, image_b_rgb, 1 - alpha, 0)

height, width = sample_rgb.shape[:2]
M = cv2.getRotationMatrix2D((width // 2, height // 2), 4, 1.0)
shifted_rgb = cv2.warpAffine(sample_rgb, M, (width, height), borderMode=cv2.BORDER_REFLECT)

kp_a, kp_b, good_matches = match_features(sample_rgb, shifted_rgb, method='ORB')
H, inlier_mask = estimate_homography(kp_a, kp_b, good_matches)

print(f"Keypoints A/B: {len(kp_a)} / {len(kp_b)}")
print(f"Good matches: {len(good_matches)}")
print(f"Homography found: {H is not None}")

if good_matches:
    match_vis_bgr = cv2.drawMatches(
        cv2.cvtColor(sample_rgb, cv2.COLOR_RGB2BGR), kp_a,
        cv2.cvtColor(shifted_rgb, cv2.COLOR_RGB2BGR), kp_b,
        good_matches[:30], None,
        flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS,
    )
    show_rgb(cv2.cvtColor(match_vis_bgr, cv2.COLOR_BGR2RGB), 'ORB Feature Matches', figsize=(14, 6))

if H is not None:
    warped_rgb = cv2.warpPerspective(sample_rgb, H, (width, height))
    blended_rgb = alpha_blend(warped_rgb, shifted_rgb, alpha=0.5)
    show_rgb(blended_rgb, 'Warped + Blended Alignment')

"""## 12-13. Exposure Stacking and Tone Mapping

For real HDR, capture multiple frames at different exposure values while the scene is steady. This demo simulates exposure brackets from one image so the processing pattern is clear.
"""

def simulate_exposure_stack(image_rgb, exposure_factors=(0.5, 1.0, 1.8)):
    return [cv2.convertScaleAbs(image_rgb, alpha=factor, beta=0) for factor in exposure_factors]


def merge_exposures_mertens(images_rgb):
    images_bgr = [cv2.cvtColor(img, cv2.COLOR_RGB2BGR) for img in images_rgb]
    merge = cv2.createMergeMertens()
    fused = merge.process(images_bgr)
    fused_8bit = np.clip(fused * 255, 0, 255).astype(np.uint8)
    return cv2.cvtColor(fused_8bit, cv2.COLOR_BGR2RGB)


def tonemap_from_hdr(images_rgb, exposure_times=None, gamma=1.4):
    if exposure_times is None:
        exposure_times = np.array([1 / 60, 1 / 30, 1 / 15], dtype=np.float32)
    images_bgr = [cv2.cvtColor(img, cv2.COLOR_RGB2BGR) for img in images_rgb]
    merge_debevec = cv2.createMergeDebevec()
    hdr = merge_debevec.process(images_bgr, times=exposure_times.copy())
    tonemap = cv2.createTonemap(gamma=gamma)
    ldr = tonemap.process(hdr)
    ldr_8bit = np.clip(ldr * 255, 0, 255).astype(np.uint8)
    return cv2.cvtColor(ldr_8bit, cv2.COLOR_BGR2RGB)

exposure_stack = simulate_exposure_stack(sample_rgb)
fused_rgb = merge_exposures_mertens(exposure_stack)

fig, axes = plt.subplots(1, 4, figsize=(18, 5))
for ax, img, title in zip(axes, exposure_stack + [fused_rgb], ['Under', 'Normal', 'Over', 'Mertens Fusion']):
    ax.imshow(img)
    ax.set_title(title)
    ax.axis('off')
plt.tight_layout()
plt.show()

"""## 14-16. Centroid Tracking, Kalman Filters, and Optical Flow

Centroid tracking is a simple object identity baseline. A Kalman filter smooths noisy detections and predicts short occlusions. Optical flow estimates pixel motion between adjacent frames.
"""

class CentroidTracker:
    def __init__(self, max_disappeared=10, max_distance=80):
        self.next_object_id = 0
        self.objects = OrderedDict()
        self.disappeared = OrderedDict()
        self.max_disappeared = max_disappeared
        self.max_distance = max_distance

    def register(self, centroid):
        self.objects[self.next_object_id] = centroid
        self.disappeared[self.next_object_id] = 0
        self.next_object_id += 1

    def deregister(self, object_id):
        del self.objects[object_id]
        del self.disappeared[object_id]

    def update(self, boxes):
        if len(boxes) == 0:
            for object_id in list(self.disappeared.keys()):
                self.disappeared[object_id] += 1
                if self.disappeared[object_id] > self.max_disappeared:
                    self.deregister(object_id)
            return self.objects

        input_centroids = np.zeros((len(boxes), 2), dtype='int')
        for i, (x1, y1, x2, y2) in enumerate(boxes):
            input_centroids[i] = ((x1 + x2) // 2, (y1 + y2) // 2)

        if len(self.objects) == 0:
            for centroid in input_centroids:
                self.register(tuple(centroid))
            return self.objects

        object_ids = list(self.objects.keys())
        object_centroids = np.array(list(self.objects.values()))
        distances = np.linalg.norm(object_centroids[:, None, :] - input_centroids[None, :, :], axis=2)

        rows = distances.min(axis=1).argsort()
        cols = distances.argmin(axis=1)[rows]
        used_rows, used_cols = set(), set()

        for row, col in zip(rows, cols):
            if row in used_rows or col in used_cols or distances[row, col] > self.max_distance:
                continue
            object_id = object_ids[row]
            self.objects[object_id] = tuple(input_centroids[col])
            self.disappeared[object_id] = 0
            used_rows.add(row)
            used_cols.add(col)

        unused_rows = set(range(distances.shape[0])) - used_rows
        unused_cols = set(range(distances.shape[1])) - used_cols

        for row in unused_rows:
            object_id = object_ids[row]
            self.disappeared[object_id] += 1
            if self.disappeared[object_id] > self.max_disappeared:
                self.deregister(object_id)

        for col in unused_cols:
            self.register(tuple(input_centroids[col]))

        return self.objects


def make_kalman_filter(initial_x, initial_y):
    kf = cv2.KalmanFilter(4, 2)
    kf.measurementMatrix = np.array([[1, 0, 0, 0], [0, 1, 0, 0]], np.float32)
    kf.transitionMatrix = np.array([[1, 0, 1, 0], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]], np.float32)
    kf.processNoiseCov = np.eye(4, dtype=np.float32) * 0.03
    kf.measurementNoiseCov = np.eye(2, dtype=np.float32) * 0.5
    kf.statePre = np.array([[initial_x], [initial_y], [0], [0]], np.float32)
    kf.statePost = kf.statePre.copy()
    return kf


def track_with_kalman(kf, measured_x=None, measured_y=None):
    prediction = kf.predict()
    if measured_x is not None and measured_y is not None:
        measurement = np.array([[np.float32(measured_x)], [np.float32(measured_y)]])
        corrected = kf.correct(measurement)
        return tuple(corrected[:2].ravel()), tuple(prediction[:2].ravel())
    return None, tuple(prediction[:2].ravel())


def dense_optical_flow(prev_rgb, next_rgb):
    prev_gray = to_gray(prev_rgb)
    next_gray = to_gray(next_rgb)
    flow = cv2.calcOpticalFlowFarneback(prev_gray, next_gray, None, 0.5, 3, 15, 3, 5, 1.2, 0)
    magnitude, angle = cv2.cartToPolar(flow[..., 0], flow[..., 1])
    hsv = np.zeros((*prev_gray.shape, 3), dtype=np.uint8)
    hsv[..., 0] = angle * 180 / np.pi / 2
    hsv[..., 1] = 255
    hsv[..., 2] = cv2.normalize(magnitude, None, 0, 255, cv2.NORM_MINMAX)
    return cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB), flow

# Centroid and Kalman demo with synthetic detections.
tracker = CentroidTracker(max_disappeared=2, max_distance=60)
detections_by_frame = [
    [(100, 80, 180, 150), (360, 120, 430, 190)],
    [(115, 90, 195, 160), (345, 125, 415, 195)],
    [(130, 100, 210, 170)],
]
for frame_idx, boxes in enumerate(detections_by_frame):
    objects = tracker.update(boxes)
    print(f"Frame {frame_idx}: {dict(objects)}")

kf = make_kalman_filter(100, 80)
for measurement in [(110, 86), (124, 94), None, (151, 111)]:
    corrected, predicted = track_with_kalman(kf, *(measurement or (None, None)))
    print(f"measurement={measurement}, predicted={tuple(round(v, 1) for v in predicted)}, corrected={None if corrected is None else tuple(round(v, 1) for v in corrected)}")

shifted_for_flow = np.roll(sample_rgb, shift=8, axis=1)
flow_vis_rgb, flow = dense_optical_flow(sample_rgb, shifted_for_flow)
show_rgb(flow_vis_rgb, 'Dense Optical Flow Visualization')

"""## Practical Order of Operations

For a real project, a healthy default pipeline is: acquire frame, validate frame, resize/normalize, optionally denoise, enhance contrast only if needed, run detection or edge/features, post-process outliers, track over time, then draw overlays last so annotations do not contaminate later vision steps.

# Recommended YOLO11 Tracking Path for Jetson Nano

Switched from YOLOv8 to YOLO11. For Jetson Nano, keep using the nano weights: `yolo11n.pt` for detection/tracking and `yolo11n-cls.pt` for classification.

Recommended honest baseline: start with **pretrained `yolo11n.pt` + ByteTrack**. Do not train first. First prove that the camera pipeline, FPS, detection, tracking IDs, and movement trails work.

Use your dataset later only if pretrained YOLO fails on your target scene. For YOLO training, the dataset must have bounding-box labels. The VeRi dataset is more useful later for vehicle re-identification, not basic vehicle detection.

About Lab color space: Lab/CLAHE can help under bad lighting, but it is not automatically better for YOLO. Pretrained YOLO expects normal RGB/BGR-like images. Use Lab enhancement as an optional A/B test, not as the default pipeline.
"""

# Install Ultralytics in Colab if needed.
# On Jetson Nano, installation is more sensitive because PyTorch/CUDA versions must match the JetPack version.
!pip install -q ultralytics

from ultralytics import YOLO
from collections import defaultdict, deque
import time

# COCO class IDs used by pretrained YOLO11 models:
# 2=car, 3=motorcycle, 5=bus, 7=truck
VEHICLE_CLASS_IDS = [2, 3, 5, 7]

YOLO_MODEL_NAME = 'yolo11n.pt'   # Nano model. Best first choice for Jetson Nano.
TRACKER_CONFIG = 'bytetrack.yaml'
IMG_SIZE = 320                   # Use 320 on Jetson Nano first. Try 416/640 only if FPS is okay.
CONF_THRESHOLD = 0.35

model = YOLO(YOLO_MODEL_NAME)
print(f'Loaded model: {YOLO_MODEL_NAME}')

"""## Optional Lab/CLAHE Preprocessing

Use this only when the image is too dark, too bright, or has harsh shadows. Keep it off first. If you turn it on, compare FPS and detection quality against the original feed.
"""

def enhance_bgr_with_lab_clahe(frame_bgr, clip_limit=2.0, tile_grid_size=(8, 8)):
    """Enhance luminance in Lab space while keeping color channels stable."""
    lab = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2LAB)
    l_channel, a_channel, b_channel = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=tile_grid_size)
    l_enhanced = clahe.apply(l_channel)
    enhanced_lab = cv2.merge((l_enhanced, a_channel, b_channel))
    return cv2.cvtColor(enhanced_lab, cv2.COLOR_LAB2BGR)


def maybe_preprocess_frame(frame_bgr, use_lab_clahe=False):
    if use_lab_clahe:
        return enhance_bgr_with_lab_clahe(frame_bgr)
    return frame_bgr

# Quick visual A/B on the existing sample image from earlier sections.
if 'sample_rgb' in globals():
    sample_bgr = cv2.cvtColor(sample_rgb, cv2.COLOR_RGB2BGR)
    enhanced_bgr = enhance_bgr_with_lab_clahe(sample_bgr)

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    axes[0].imshow(cv2.cvtColor(sample_bgr, cv2.COLOR_BGR2RGB))
    axes[0].set_title('Original')
    axes[0].axis('off')
    axes[1].imshow(cv2.cvtColor(enhanced_bgr, cv2.COLOR_BGR2RGB))
    axes[1].set_title('Lab CLAHE Enhanced')
    axes[1].axis('off')
    plt.tight_layout()
    plt.show()
else:
    print('sample_rgb is not available. Run the previous demo-image helper cell first if you want the A/B preview.')

"""## Tracking Loop with Movement Trails

This loop reads frames, optionally enhances lighting, runs YOLO tracking, draws bounding boxes, stable track IDs, centroids, trails, direction, and approximate speed in pixels per second.
"""

def center_of_box_xyxy(box_xyxy):
    x1, y1, x2, y2 = box_xyxy
    return int((x1 + x2) / 2), int((y1 + y2) / 2)


def draw_tracking_result(frame_bgr, result, track_history, previous_centers, previous_times, max_trail=30):
    now = time.time()
    annotated = frame_bgr.copy()

    if result.boxes is None or result.boxes.id is None:
        return annotated

    boxes = result.boxes.xyxy.cpu().numpy()
    track_ids = result.boxes.id.int().cpu().tolist()
    class_ids = result.boxes.cls.int().cpu().tolist()
    confidences = result.boxes.conf.cpu().numpy()

    for box, track_id, class_id, conf in zip(boxes, track_ids, class_ids, confidences):
        x1, y1, x2, y2 = box.astype(int)
        cx, cy = center_of_box_xyxy((x1, y1, x2, y2))

        track_history[track_id].append((cx, cy))
        if len(track_history[track_id]) > max_trail:
            track_history[track_id].popleft()

        speed_px_per_sec = 0.0
        direction = ''
        if track_id in previous_centers:
            prev_cx, prev_cy = previous_centers[track_id]
            dt = max(now - previous_times.get(track_id, now), 1e-6)
            dx, dy = cx - prev_cx, cy - prev_cy
            speed_px_per_sec = math.sqrt(dx * dx + dy * dy) / dt
            if abs(dx) > abs(dy):
                direction = 'right' if dx > 0 else 'left'
            else:
                direction = 'down' if dy > 0 else 'up'

        previous_centers[track_id] = (cx, cy)
        previous_times[track_id] = now

        color = (0, 255, 0)
        cv2.rectangle(annotated, (x1, y1), (x2, y2), color, 2)
        cv2.circle(annotated, (cx, cy), 4, (0, 0, 255), -1)

        class_name = model.names.get(class_id, str(class_id))
        label = f'ID {track_id} {class_name} {conf:.2f}'
        motion = f'{direction} {speed_px_per_sec:.0f}px/s' if direction else 'new track'
        cv2.putText(annotated, label, (x1, max(20, y1 - 24)), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255, 255, 255), 2, cv2.LINE_AA)
        cv2.putText(annotated, motion, (x1, max(20, y1 - 6)), cv2.FONT_HERSHEY_SIMPLEX, 0.50, (255, 255, 0), 2, cv2.LINE_AA)

        trail = list(track_history[track_id])
        for i in range(1, len(trail)):
            cv2.line(annotated, trail[i - 1], trail[i], (0, 255, 255), 2)

    return annotated

def run_yolo11_tracking(
    source=0,
    use_lab_clahe=False,
    classes=VEHICLE_CLASS_IDS,
    imgsz=IMG_SIZE,
    conf=CONF_THRESHOLD,
    tracker=TRACKER_CONFIG,
    max_frames=None,
    display=True,
    save_path=None,
):
    """Run YOLO11n + ByteTrack on webcam, video file, or CSI-captured frames.

    source can be:
    - 0 for a USB webcam
    - a video path like 'traffic.mp4'
    - a camera/GStreamer source if your OpenCV build supports it
    """
    cap = cv2.VideoCapture(source)
    if not cap.isOpened():
        print(f'Could not open video source: {source}')
        return

    writer = None
    if save_path is not None:
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) or 640
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) or 480
        fps = cap.get(cv2.CAP_PROP_FPS)
        fps = fps if fps and fps > 1 else 20
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        writer = cv2.VideoWriter(save_path, fourcc, fps, (width, height))

    track_history = defaultdict(lambda: deque(maxlen=30))
    previous_centers = {}
    previous_times = {}
    frame_count = 0
    start_time = time.time()

    try:
        while True:
            ok, frame_bgr = cap.read()
            if not ok:
                break

            input_bgr = maybe_preprocess_frame(frame_bgr, use_lab_clahe=use_lab_clahe)

            results = model.track(
                input_bgr,
                persist=True,
                tracker=tracker,
                imgsz=imgsz,
                conf=conf,
                classes=classes,
                verbose=False,
            )

            annotated = draw_tracking_result(frame_bgr, results[0], track_history, previous_centers, previous_times)

            frame_count += 1
            elapsed = max(time.time() - start_time, 1e-6)
            fps_text = f'FPS: {frame_count / elapsed:.1f} | Lab: {use_lab_clahe}'
            cv2.putText(annotated, fps_text, (15, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (0, 255, 255), 2, cv2.LINE_AA)

            if writer is not None:
                writer.write(annotated)

            if display:
                if not safe_imshow('YOLO11 Tracking', annotated):
                    print('Display is unavailable here. Set display=False and save_path="output.mp4" in headless/Colab environments.')
                    break
                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break

            if max_frames is not None and frame_count >= max_frames:
                break
    finally:
        cap.release()
        if writer is not None:
            writer.release()
        cv2.destroyAllWindows()

    print(f'Processed {frame_count} frames.')

print('Tracking function ready.')
print('Local webcam example: run_yolo11_tracking(source=0, use_lab_clahe=False)')
print('Video file example:   run_yolo11_tracking(source="traffic.mp4", display=False, save_path="tracked_output.mp4")')

"""## What to Try First

1. Test pretrained tracking without your dataset.
2. Keep `use_lab_clahe=False` first.
3. Use `imgsz=320` on Jetson Nano.
4. If the scene is too dark or high-contrast, test `use_lab_clahe=True` and compare actual detection quality.
5. If pretrained YOLO misses your objects, then prepare a bounding-box dataset and fine-tune `yolo11n.pt`.
"""

# Colab/headless-safe example for a video file:
# Upload a video named traffic.mp4, then run:
# run_yolo11_tracking(source='traffic.mp4', use_lab_clahe=False, display=False, save_path='tracked_output.mp4', max_frames=300)

# Local/Jetson webcam example:
# run_yolo11_tracking(source=0, use_lab_clahe=False, display=True)

# If lighting is bad, compare this version:
# run_yolo11_tracking(source=0, use_lab_clahe=True, display=True)

"""## When to Use Your Dataset

Use a custom dataset when pretrained YOLO is not good enough. For YOLO, your dataset needs bounding boxes, not only cropped vehicle images.

Expected YOLO format:

```text
dataset/
  images/train/
  images/val/
  labels/train/
  labels/val/
  data.yaml
```

Each label file contains normalized boxes:

```text
class_id x_center y_center width height
```

Fine-tuning example:

```python
custom_model = YOLO('yolo11n.pt')
custom_model.train(data='data.yaml', epochs=50, imgsz=320, batch=16, device=0)
```

Then use the trained weights for tracking:

```python
model = YOLO('runs/detect/train/weights/best.pt')
run_yolo11_tracking(source=0)
```

VeRi is still useful, but more for vehicle re-identification: answering “is this the same car?” after detection/tracking already works.

# Use the Cleaned VeRi Dataset Now with YOLO11

This uses the cleaned VeRi images immediately, but for the correct task: **vehicle-ID classification / Re-ID style learning** using `yolo11n-cls.pt`.

Honest limitation: this is **not** object detection training. YOLO detection training needs bounding-box labels. The cleaned VeRi images are already cropped around vehicles, so they are better for teaching a model “which vehicle ID is this?” rather than “where is the vehicle in a big frame?”

Practical architecture later:

```text
Traffic video
-> YOLO11n detector finds vehicles and tracks boxes
-> crop each vehicle box
-> YOLO11n-cls / Re-ID model identifies or compares the vehicle crop
```
"""

# Build a YOLO11 classification dataset from the cleaned VeRi image lists.
# Folder format expected by Ultralytics classification:
# veri_yolo_cls/
#   train/<vehicle_id>/*.jpg
#   val/<vehicle_id>/*.jpg

import shutil
from pathlib import Path
from collections import Counter

YOLO_CLS_DATASET_DIR = Path('veri_yolo_cls')
MAX_CLASSES_FOR_QUICK_TEST = 30       # Set to None to use all classes. Keep small for first experiment.
MAX_IMAGES_PER_CLASS = 60             # Set to None to use all images per selected class.
MIN_IMAGES_PER_CLASS = 2              # Skip IDs with too few images for train/val.
VAL_RATIO = 0.2
RANDOM_SEED = 42


def vehicle_id_from_filename(filename):
    return filename.split('_')[0]


def collect_images_by_id(image_names):
    by_id = {}
    for name in image_names:
        vehicle_id = vehicle_id_from_filename(name)
        by_id.setdefault(vehicle_id, []).append(name)
    return by_id


def prepare_yolo_cls_dataset(
    image_names,
    source_dir,
    output_dir=YOLO_CLS_DATASET_DIR,
    max_classes=MAX_CLASSES_FOR_QUICK_TEST,
    max_images_per_class=MAX_IMAGES_PER_CLASS,
    min_images_per_class=MIN_IMAGES_PER_CLASS,
    val_ratio=VAL_RATIO,
    seed=RANDOM_SEED,
):
    rng = np.random.default_rng(seed)
    output_dir = Path(output_dir)
    source_dir = Path(source_dir)

    if output_dir.exists():
        shutil.rmtree(output_dir)

    by_id = collect_images_by_id(image_names)
    eligible = {vid: imgs for vid, imgs in by_id.items() if len(imgs) >= min_images_per_class}
    selected_ids = sorted(eligible.keys(), key=lambda vid: len(eligible[vid]), reverse=True)
    if max_classes is not None:
        selected_ids = selected_ids[:max_classes]

    class_counts = []
    for vehicle_id in selected_ids:
        imgs = list(eligible[vehicle_id])
        rng.shuffle(imgs)
        if max_images_per_class is not None:
            imgs = imgs[:max_images_per_class]

        n_val = max(1, int(round(len(imgs) * val_ratio)))
        val_imgs = imgs[:n_val]
        train_imgs = imgs[n_val:]

        if not train_imgs:
            train_imgs, val_imgs = imgs[:-1], imgs[-1:]

        for split, split_imgs in [('train', train_imgs), ('val', val_imgs)]:
            class_dir = output_dir / split / vehicle_id
            class_dir.mkdir(parents=True, exist_ok=True)
            for img_name in split_imgs:
                src = source_dir / img_name
                dst = class_dir / img_name
                if src.exists():
                    shutil.copy2(src, dst)

        class_counts.append({
            'vehicle_id': vehicle_id,
            'train_images': len(train_imgs),
            'val_images': len(val_imgs),
            'total_images': len(imgs),
        })

    df_cls_summary = pd.DataFrame(class_counts)
    return output_dir, df_cls_summary

if 'final_clean_train_images' not in globals() or not final_clean_train_images:
    raise RuntimeError('Run the cleaning cells first so final_clean_train_images is available.')

cls_dataset_dir, df_cls_summary = prepare_yolo_cls_dataset(final_clean_train_images, train_dir)
print(f'YOLO classification dataset created at: {cls_dataset_dir.resolve()}')
print(f'Classes selected: {len(df_cls_summary)}')
display(df_cls_summary.head(10))
print(df_cls_summary[['train_images', 'val_images', 'total_images']].sum())

"""## Train YOLO11n Classification on the Cleaned Dataset

Start small. Use 10-20 epochs and a limited number of classes first. If it runs correctly, increase `MAX_CLASSES_FOR_QUICK_TEST` or set it to `None` and rebuild the dataset.

For Jetson Nano, train in Colab and deploy only the trained model for inference.
"""

# Train a lightweight YOLO11 classification model using your cleaned vehicle crops.
# This is a classification/Re-ID-style step, not detection training.

from ultralytics import YOLO

cls_model = YOLO('yolo11n-cls.pt')

cls_results = cls_model.train(
    data=str(cls_dataset_dir),
    epochs=10,
    imgsz=224,
    batch=32,
    device=0 if torch.cuda.is_available() else 'cpu',
    workers=2,
    project='runs/classify',
    name='veri_yolo11n_cls',
)

"""## Test the Trained Classifier on a Cleaned Image

After training, the best weights are usually saved under:

```text
runs/classify/veri_yolo11n_cls/weights/best.pt
```
"""

BEST_CLS_WEIGHTS = 'runs/classify/runs/classify/veri_yolo11n_cls/weights/best.pt'

trained_cls_model = YOLO(BEST_CLS_WEIGHTS)

if final_clean_train_images:
    test_image_path = os.path.join(train_dir, final_clean_train_images[0])
    pred = trained_cls_model.predict(test_image_path, imgsz=224, verbose=False)[0]

    top1_idx = int(pred.probs.top1)
    top1_conf = float(pred.probs.top1conf)
    predicted_vehicle_id = trained_cls_model.names[top1_idx]
    true_vehicle_id = vehicle_id_from_filename(os.path.basename(test_image_path))

    print(f'True vehicle ID:      {true_vehicle_id}')
    print(f'Predicted vehicle ID: {predicted_vehicle_id}')
    print(f'Confidence:           {top1_conf:.3f}')
else:
    print('No cleaned training images available for classifier test.')

"""## Connect Classifier with YOLO Tracking Later

Once tracking works, every YOLO detection box can be cropped and passed to the classifier. This gives a rough “which known vehicle ID is this crop closest to?” result.

This works best only when the vehicles in the video are similar to or actually present in the training dataset. If your traffic video contains unseen vehicles, this classifier will still force a prediction into one of the known VeRi IDs, so treat it carefully.
"""

def classify_vehicle_crop(frame_bgr, box_xyxy, classifier_model, imgsz=224):
    x1, y1, x2, y2 = [int(v) for v in box_xyxy]
    height, width = frame_bgr.shape[:2]
    x1 = max(0, min(x1, width - 1))
    x2 = max(0, min(x2, width - 1))
    y1 = max(0, min(y1, height - 1))
    y2 = max(0, min(y2, height - 1))

    if x2 <= x1 or y2 <= y1:
        return None

    crop_bgr = frame_bgr[y1:y2, x1:x2]
    pred = classifier_model.predict(crop_bgr, imgsz=imgsz, verbose=False)[0]
    top1_idx = int(pred.probs.top1)
    top1_conf = float(pred.probs.top1conf)
    return classifier_model.names[top1_idx], top1_conf

print('classify_vehicle_crop is ready for use after YOLO tracking detects a vehicle box.')

"""## If You Actually Want to Fine-Tune YOLO Detection

You need bounding-box labels. Check whether your dataset folder has annotations such as `.txt`, `.xml`, or `.json`. If it does not, you must label images in Roboflow, CVAT, Label Studio, or makesense.ai, then export YOLO format.
"""

def audit_detection_labels(dataset_root):
    dataset_root = Path(dataset_root)
    label_files = []
    for pattern in ('*.txt', '*.xml', '*.json', '*.csv'):
        label_files.extend(dataset_root.rglob(pattern))

    df_labels = pd.DataFrame({
        'path': [str(p) for p in label_files],
        'suffix': [p.suffix.lower() for p in label_files],
    })
    print(f'Found {len(df_labels)} possible annotation files under {dataset_root}')
    if not df_labels.empty:
        display(df_labels['suffix'].value_counts().rename_axis('suffix').reset_index(name='count'))
        display(df_labels.head(20))
    return df_labels

# Run this after dataset download if you want to check for detection labels.
# df_detection_label_audit = audit_detection_labels(path)

"""# Use Your Own Trained Model on Traffic Video

This is the combined pipeline:

```text
traffic video
-> YOLO11 detector/tracker (`yolo11n.pt`) finds vehicle boxes
-> crop each vehicle box
-> your trained classifier (`runs/classify/veri_yolo11n_cls/weights/best.pt`) predicts vehicle ID from the crop
-> draw track ID + predicted vehicle ID on the video
```

Important: the detector is still pretrained unless you also train a detection model with bounding-box labels. Your custom model here is the classification/Re-ID-style model trained from cleaned VeRi images.
"""

CUSTOM_CLS_WEIGHTS = 'runs/classify/veri_yolo11n_cls/weights/best.pt'


def load_custom_vehicle_classifier(weights_path=CUSTOM_CLS_WEIGHTS):
    weights_path = Path(weights_path)
    if not weights_path.exists():
        raise FileNotFoundError(
            f'Custom classifier weights not found: {weights_path}\n'
            'Run the YOLO11 classification training cell first, then try again.'
        )
    return YOLO(str(weights_path))

# Uncomment after training finishes:
# custom_vehicle_classifier = load_custom_vehicle_classifier()
# print(custom_vehicle_classifier.names)

def classify_vehicle_crop_cached(
    frame_bgr,
    box_xyxy,
    classifier_model,
    track_id,
    label_cache,
    frame_index,
    classify_every_n_frames=10,
    imgsz=224,
):
    """Classify a tracked vehicle crop, but cache the label to save compute."""
    cached = label_cache.get(track_id)
    if cached is not None and frame_index % classify_every_n_frames != 0:
        return cached

    result = classify_vehicle_crop(frame_bgr, box_xyxy, classifier_model, imgsz=imgsz)
    if result is None:
        return cached

    vehicle_id, confidence = result
    label_cache[track_id] = (vehicle_id, confidence)
    return label_cache[track_id]


def draw_tracking_with_custom_id(
    frame_bgr,
    result,
    track_history,
    previous_centers,
    previous_times,
    classifier_model,
    label_cache,
    frame_index,
    classify_every_n_frames=10,
    max_trail=30,
):
    now = time.time()
    annotated = frame_bgr.copy()

    if result.boxes is None or result.boxes.id is None:
        return annotated

    boxes = result.boxes.xyxy.cpu().numpy()
    track_ids = result.boxes.id.int().cpu().tolist()
    class_ids = result.boxes.cls.int().cpu().tolist()
    confidences = result.boxes.conf.cpu().numpy()

    for box, track_id, class_id, det_conf in zip(boxes, track_ids, class_ids, confidences):
        x1, y1, x2, y2 = box.astype(int)
        cx, cy = center_of_box_xyxy((x1, y1, x2, y2))

        track_history[track_id].append((cx, cy))
        if len(track_history[track_id]) > max_trail:
            track_history[track_id].popleft()

        speed_px_per_sec = 0.0
        direction = ''
        if track_id in previous_centers:
            prev_cx, prev_cy = previous_centers[track_id]
            dt = max(now - previous_times.get(track_id, now), 1e-6)
            dx, dy = cx - prev_cx, cy - prev_cy
            speed_px_per_sec = math.sqrt(dx * dx + dy * dy) / dt
            direction = ('right' if dx > 0 else 'left') if abs(dx) > abs(dy) else ('down' if dy > 0 else 'up')

        previous_centers[track_id] = (cx, cy)
        previous_times[track_id] = now

        custom_pred = classify_vehicle_crop_cached(
            frame_bgr,
            (x1, y1, x2, y2),
            classifier_model,
            track_id,
            label_cache,
            frame_index,
            classify_every_n_frames=classify_every_n_frames,
        )

        class_name = model.names.get(class_id, str(class_id))
        if custom_pred is None:
            custom_text = 'custom ID: ...'
        else:
            vehicle_id, cls_conf = custom_pred
            custom_text = f'custom ID: {vehicle_id} ({cls_conf:.2f})'

        cv2.rectangle(annotated, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.circle(annotated, (cx, cy), 4, (0, 0, 255), -1)
        cv2.putText(annotated, f'Track {track_id} {class_name} det:{det_conf:.2f}', (x1, max(20, y1 - 42)), cv2.FONT_HERSHEY_SIMPLEX, 0.52, (255, 255, 255), 2, cv2.LINE_AA)
        cv2.putText(annotated, custom_text, (x1, max(20, y1 - 24)), cv2.FONT_HERSHEY_SIMPLEX, 0.52, (255, 255, 0), 2, cv2.LINE_AA)
        motion = f'{direction} {speed_px_per_sec:.0f}px/s' if direction else 'new track'
        cv2.putText(annotated, motion, (x1, max(20, y1 - 6)), cv2.FONT_HERSHEY_SIMPLEX, 0.48, (0, 255, 255), 2, cv2.LINE_AA)

        trail = list(track_history[track_id])
        for i in range(1, len(trail)):
            cv2.line(annotated, trail[i - 1], trail[i], (0, 255, 255), 2)

    return annotated

def run_yolo11_tracking_with_custom_classifier(
    source,
    classifier_weights=CUSTOM_CLS_WEIGHTS,
    use_lab_clahe=False,
    classes=VEHICLE_CLASS_IDS,
    imgsz=IMG_SIZE,
    conf=CONF_THRESHOLD,
    tracker=TRACKER_CONFIG,
    classify_every_n_frames=10,
    max_frames=None,
    display=False,
    save_path='tracked_with_custom_model.mp4',
):
    """Track vehicles with YOLO11 and classify each crop with your trained model."""
    classifier_model = load_custom_vehicle_classifier(classifier_weights)

    cap = cv2.VideoCapture(source)
    if not cap.isOpened():
        print(f'Could not open video source: {source}')
        return

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) or 640
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) or 480
    fps = cap.get(cv2.CAP_PROP_FPS)
    fps = fps if fps and fps > 1 else 20

    writer = None
    if save_path is not None:
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        writer = cv2.VideoWriter(save_path, fourcc, fps, (width, height))

    track_history = defaultdict(lambda: deque(maxlen=30))
    previous_centers = {}
    previous_times = {}
    label_cache = {}
    frame_count = 0
    start_time = time.time()

    try:
        while True:
            ok, frame_bgr = cap.read()
            if not ok:
                break

            input_bgr = maybe_preprocess_frame(frame_bgr, use_lab_clahe=use_lab_clahe)
            results = model.track(
                input_bgr,
                persist=True,
                tracker=tracker,
                imgsz=imgsz,
                conf=conf,
                classes=classes,
                verbose=False,
            )

            annotated = draw_tracking_with_custom_id(
                frame_bgr,
                results[0],
                track_history,
                previous_centers,
                previous_times,
                classifier_model,
                label_cache,
                frame_count,
                classify_every_n_frames=classify_every_n_frames,
            )

            frame_count += 1
            elapsed = max(time.time() - start_time, 1e-6)
            fps_text = f'FPS: {frame_count / elapsed:.1f} | detector: yolo11n | custom cls: ON'
            cv2.putText(annotated, fps_text, (15, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.70, (0, 255, 255), 2, cv2.LINE_AA)

            if writer is not None:
                writer.write(annotated)

            if display:
                if not safe_imshow('YOLO11 + Custom Classifier', annotated):
                    print('Display unavailable. Use display=False and inspect the saved video.')
                    break
                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break

            if max_frames is not None and frame_count >= max_frames:
                break
    finally:
        cap.release()
        if writer is not None:
            writer.release()
        if display: # Conditionally call destroyAllWindows
            cv2.destroyAllWindows()

    print(f'Processed {frame_count} frames.')
    if save_path is not None:
        print(f'Saved result to: {save_path}')

print('Custom classifier video pipeline is ready.')

"""## Run Your Own Model on a Video

Run this after:

1. The YOLO11 tracking setup cells are run.
2. The cleaned VeRi classification dataset is created.
3. `yolo11n-cls.pt` has been trained and `runs/classify/veri_yolo11n_cls/weights/best.pt` exists.
4. `VIDEO_PATH` points to your uploaded traffic video.
"""

run_yolo11_tracking_with_custom_classifier(
    source="/content/NT.mp4",
    classifier_weights='runs/classify/runs/classify/veri_yolo11n_cls/weights/best.pt',
    use_lab_clahe=False,
    display=False,
    save_path='tracked_with_custom_model.mp4',
    max_frames=300,
    classify_every_n_frames=10,
)

# Preview in Colab after it finishes:
from IPython.display import HTML
from base64 import b64encode
mp4 = open('tracked_with_custom_model.mp4', 'rb').read()
video_data = b64encode(mp4).decode()
HTML('<video width="720" controls><source src="data:video/mp4;base64,' + video_data + '" type="video/mp4"></video>')



"""# RTSP Stream Debug and Run

Use this section before running YOLO on an RTSP camera stream.

Important: `rtsp://10.0.11.176:8554/vdo5` is a private-network address. It usually works only from a laptop, local Jupyter server, or Jetson Nano connected to the same network. A normal Colab runtime cannot reach this IP unless you set up VPN/tunneling into that network.
"""

RTSP_URL = 'rtsp://10.0.11.176:8554/vdo5'
print(RTSP_URL)

# Step 1: check whether this notebook machine can reach the RTSP host.
# If this fails in Colab, run the notebook locally or on Jetson Nano instead.
import socket
from urllib.parse import urlparse

parsed = urlparse(RTSP_URL)
host = parsed.hostname
port = parsed.port or 554

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(5)
try:
    sock.connect((host, port))
    print(f'Connected to {host}:{port}. Network path is OK.')
except Exception as exc:
    print(f'Cannot connect to {host}:{port}: {exc}')
    print('Check same Wi-Fi/LAN/VPN, firewall, RTSP server status, and the stream URL.')
finally:
    sock.close()

# Step 2: force OpenCV/FFmpeg to use TCP for RTSP, which is often more reliable than UDP.
# This environment variable must be set before cv2.VideoCapture opens the stream.
import os
os.environ['OPENCV_FFMPEG_CAPTURE_OPTIONS'] = 'rtsp_transport;tcp|stimeout;5000000|max_delay;500000'
print(os.environ['OPENCV_FFMPEG_CAPTURE_OPTIONS'])

# Step 3: open the RTSP stream and read one frame.
cap = cv2.VideoCapture(RTSP_URL, cv2.CAP_FFMPEG)
print('Opened:', cap.isOpened())

ok, frame_bgr = cap.read()
print('Read frame:', ok)
if ok:
    print('Frame shape:', frame_bgr.shape)
    cv2.imwrite('rtsp_first_frame.jpg', frame_bgr)
    print('Saved preview frame: rtsp_first_frame.jpg')
else:
    print('No frame received. Try VLC/ffplay, check credentials, or run from the same network as the camera.')

cap.release()

# Step 4: preview the first frame inside the notebook if it was captured.
preview = cv2.imread('rtsp_first_frame.jpg')
if preview is None:
    print('No preview image found. Step 3 did not capture a frame.')
else:
    preview_rgb = cv2.cvtColor(preview, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(10, 6))
    plt.imshow(preview_rgb)
    plt.title('RTSP First Frame')
    plt.axis('off')
    plt.show()

run_yolo11_tracking(
    source=RTSP_URL,
    use_lab_clahe=False,
    display=False,
    save_path='rtsp_tracked_pretrained.mp4',
    max_frames=300,
)

# Step 5B: run pretrained YOLO11 tracking + your custom classifier.
# Run this only after runs/classify/veri_yolo11n_cls/weights/best.pt exists.
run_yolo11_tracking_with_custom_classifier(
    source=RTSP_URL,
    classifier_weights='runs/classify/veri_yolo11n_cls/weights/best.pt',
    use_lab_clahe=False,
    display=False,
    save_path='rtsp_tracked_with_custom_model.mp4',
    max_frames=300,
    classify_every_n_frames=10,
)

# Step 6: preview an output video in a notebook.
from IPython.display import HTML
from base64 import b64encode
from pathlib import Path

output_path = Path('rtsp_tracked_pretrained.mp4')
# output_path = Path('rtsp_tracked_with_custom_model.mp4')

if not output_path.exists():
    print(f'Output video not found: {output_path}')
else:
    mp4 = output_path.read_bytes()
    video_data = b64encode(mp4).decode()
    HTML('<video width="720" controls><source src="data:video/mp4;base64,' + video_data + '" type="video/mp4"></video>')

"""## If RTSP Still Does Not Open

Try the same URL in VLC or with `ffplay` from the same machine/network:

```bash
ffplay -rtsp_transport tcp rtsp://10.0.11.176:8554/vdo5
```

If VLC/ffplay cannot open it, the issue is network/stream URL/permissions, not YOLO. If VLC can open it but OpenCV cannot, install an OpenCV build with FFmpeg or use a GStreamer pipeline on Jetson.

# ROI Zone from Your Red Line

The red area in your screenshot should be treated as a **Region of Interest (ROI)**. This lets the tracker ignore vehicles outside the useful road area and draw only the tracks that matter.

The polygon below uses normalized coordinates, so it scales to different video resolutions. You can adjust the points after previewing the overlay.
"""

# Approximate ROI polygon from your red line.
# Coordinates are normalized: (x / frame_width, y / frame_height).
# Adjust these points if the overlay is slightly off for your original video resolution.
ROI_POLYGON_NORM = np.array([
    [0.36, 0.34],  # top-left near lane entrance
    [0.54, 0.31],  # top middle
    [0.68, 0.40],  # upper-right curve
    [0.80, 0.55],  # right curve
    [0.84, 0.66],  # far right
    [0.76, 0.79],  # lower-right
    [0.43, 0.88],  # bottom-left
    [0.41, 0.72],  # left lower edge
    [0.39, 0.55],  # left middle edge
], dtype=np.float32)


def polygon_norm_to_pixels(polygon_norm, frame_shape):
    height, width = frame_shape[:2]
    polygon_px = polygon_norm.copy().astype(np.float32)
    polygon_px[:, 0] *= width
    polygon_px[:, 1] *= height
    return polygon_px.astype(np.int32)


def point_inside_polygon(point_xy, polygon_px):
    return cv2.pointPolygonTest(polygon_px, point_xy, False) >= 0


def draw_roi_polygon(frame_bgr, polygon_norm=ROI_POLYGON_NORM, color=(0, 0, 255), thickness=1):
    """Draw a thin ROI outline only, with no filled overlay."""
    polygon_px = polygon_norm_to_pixels(polygon_norm, frame_bgr.shape)
    output = frame_bgr.copy()
    cv2.polylines(output, [polygon_px], isClosed=True, color=color, thickness=thickness)
    return output, polygon_px


def count_new_tracks_in_roi(result, polygon_px, counted_track_ids):
    """Count each tracker ID once when its centroid first appears inside the ROI."""
    if result.boxes is None or result.boxes.id is None:
        return 0

    boxes = result.boxes.xyxy.cpu().numpy()
    track_ids = result.boxes.id.int().cpu().tolist()
    new_count = 0

    for box, track_id in zip(boxes, track_ids):
        x1, y1, x2, y2 = box.astype(int)
        cx, cy = center_of_box_xyxy((x1, y1, x2, y2))
        if point_inside_polygon((cx, cy), polygon_px) and track_id not in counted_track_ids:
            counted_track_ids.add(track_id)
            new_count += 1

    return new_count

print('Clean ROI helpers ready: thin outline + vehicle counting.')

def draw_tracking_with_custom_id_roi(
    frame_bgr,
    result,
    track_history,
    previous_centers,
    previous_times,
    classifier_model,
    label_cache,
    frame_index,
    polygon_norm=ROI_POLYGON_NORM,
    classify_every_n_frames=10,
    max_trail=12,
    min_vehicle_id_conf=0.50,
):
    annotated, polygon_px = draw_roi_polygon(frame_bgr, polygon_norm=polygon_norm, thickness=1)
    now = time.time()

    if result.boxes is None or result.boxes.id is None:
        return annotated

    boxes = result.boxes.xyxy.cpu().numpy()
    track_ids = result.boxes.id.int().cpu().tolist()

    for box, track_id in zip(boxes, track_ids):
        x1, y1, x2, y2 = box.astype(int)
        cx, cy = center_of_box_xyxy((x1, y1, x2, y2))

        # Filter: only keep vehicles whose centroid is inside your red ROI.
        if not point_inside_polygon((cx, cy), polygon_px):
            continue

        track_history[track_id].append((cx, cy))
        if len(track_history[track_id]) > max_trail:
            track_history[track_id].popleft()

        previous_centers[track_id] = (cx, cy)
        previous_times[track_id] = now

        custom_pred = classify_vehicle_crop_cached(
            frame_bgr,
            (x1, y1, x2, y2),
            classifier_model,
            track_id,
            label_cache,
            frame_index,
            classify_every_n_frames=classify_every_n_frames,
        )

        label = f'ID {track_id}'
        if custom_pred is not None:
            vehicle_id, cls_conf = custom_pred
            if cls_conf >= min_vehicle_id_conf:
                label += f' | V:{vehicle_id}'

        cv2.rectangle(annotated, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.circle(annotated, (cx, cy), 4, (0, 0, 255), -1)
        cv2.putText(
            annotated,
            label,
            (x1, max(20, y1 - 8)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.55,
            (255, 255, 255),
            2,
            cv2.LINE_AA,
        )

        trail = list(track_history[track_id])[-max_trail:]
        for i in range(1, len(trail)):
            cv2.line(annotated, trail[i - 1], trail[i], (0, 255, 255), 2)

    return annotated

def run_yolo11_tracking_with_custom_classifier_roi(
    source,
    classifier_weights=CUSTOM_CLS_WEIGHTS,
    use_lab_clahe=False,
    classes=VEHICLE_CLASS_IDS,
    imgsz=IMG_SIZE,
    conf=CONF_THRESHOLD,
    tracker=TRACKER_CONFIG,
    classify_every_n_frames=10,
    max_frames=None,
    display=False,
    save_path='tracked_with_custom_model_roi_count.mp4',
    polygon_norm=ROI_POLYGON_NORM,
):
    """Track/classify vehicles inside the ROI and count each track once."""
    classifier_model = load_custom_vehicle_classifier(classifier_weights)

    cap = cv2.VideoCapture(source)
    if not cap.isOpened():
        print(f'Could not open video source: {source}')
        return

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) or 640
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) or 480
    fps = cap.get(cv2.CAP_PROP_FPS)
    fps = fps if fps and fps > 1 else 20

    writer = None
    if save_path is not None:
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        writer = cv2.VideoWriter(save_path, fourcc, fps, (width, height))

    track_history = defaultdict(lambda: deque(maxlen=12))
    previous_centers = {}
    previous_times = {}
    label_cache = {}
    counted_track_ids = set()
    vehicle_count = 0
    frame_count = 0

    try:
        while True:
            ok, frame_bgr = cap.read()
            if not ok:
                break

            input_bgr = maybe_preprocess_frame(frame_bgr, use_lab_clahe=use_lab_clahe)
            results = model.track(
                input_bgr,
                persist=True,
                tracker=tracker,
                imgsz=imgsz,
                conf=conf,
                classes=classes,
                verbose=False,
            )

            polygon_px = polygon_norm_to_pixels(polygon_norm, frame_bgr.shape)
            vehicle_count += count_new_tracks_in_roi(results[0], polygon_px, counted_track_ids)

            annotated = draw_tracking_with_custom_id_roi(
                frame_bgr,
                results[0],
                track_history,
                previous_centers,
                previous_times,
                classifier_model,
                label_cache,
                frame_count,
                polygon_norm=polygon_norm,
                classify_every_n_frames=classify_every_n_frames,
            )

            cv2.putText(
                annotated,
                f'Count: {vehicle_count}',
                (20, 35),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.85,
                (0, 255, 255),
                2,
                cv2.LINE_AA,
            )

            frame_count += 1

            if writer is not None:
                writer.write(annotated)

            if display:
                if not safe_imshow('YOLO11 + Custom Classifier + ROI Count', annotated):
                    print('Display unavailable. Use display=False and inspect the saved video.')
                    break
                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break

            if max_frames is not None and frame_count >= max_frames:
                break
    finally:
        cap.release()
        if writer is not None:
            writer.release()
        cv2.destroyAllWindows()

    print(f'Processed {frame_count} frames.')
    print(f'Final vehicle count: {vehicle_count}')
    if save_path is not None:
        print(f'Saved result to: {save_path}')

print('Clean ROI counting pipeline is ready: box + ID + vehicle ID + short trail + thin ROI + Count.')

"""## Run With Your ROI

Use this after your normal YOLO11 setup and custom classifier setup are ready.
"""

#### Example with ROI + vehicle count:
run_yolo11_tracking_with_custom_classifier_roi(
    source="/content/NT.mp4",
    classifier_weights='runs/classify/runs/classify/veri_yolo11n_cls/weights/best.pt',
    use_lab_clahe=False,
    display=False,
    save_path='tracked_with_custom_model_roi_count.mp4',
    max_frames=300,
    classify_every_n_frames=10,
)

from IPython.display import HTML
from base64 import b64encode
from pathlib import Path

output_path = Path('tracked_with_custom_model_roi_count.mp4')

if not output_path.exists():
    print(f'Output video not found: {output_path}')
else:
    mp4 = output_path.read_bytes()
    video_data = b64encode(mp4).decode()
    HTML('<video width="720" controls><source src="data:video/mp4;base64,' + video_data + '" type="video/mp4"></video>')